# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4511db7882c1732508cb0635c183437f072000a1720b790cda22a3047fbe58a99f5158dc9c7bc60b733f06bf1b615b47476868b8249c795befc580de42212923

test:
  secret_key_base: 7e4f14824585a465cd8ed7e468cb0f0b521a803de6587ba6b50003d8d374396348a72fd9cc2aa1628b0e1f35f513b7abd447491dc3ad8c8656acebcb066d1c84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
