# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927e441d477d3aa3dfff8909ca46c837a4985077cd1f0328c67a27b5fa64602010a4ab8063b3037f2275a9fca9308196f0dfbb1e7fcf3cd1624cd4e7bdc89e3c

test:
  secret_key_base: 2c6802f10b07c05d1bc5ac18911de8f7bff6e1d4c9443828022cf0051b6c99878b5b5516e012a98f542aecfad01dece7de8545a4df91bd39c97f69306a034e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
