# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dca88e7c99e85b70d959ce104237d284b94f23cf30721a3c352243f73e2193a1e369f2004743991b497c8ae4887c79bfed2cb40a2b425ebe6545cd7a659aea0

test:
  secret_key_base: 99c5e72545489370af12c8aea3583e0b08f28becd31806b7daf44764cc3944f8fd513b351232dae6e3138258c2636b3b7a754a941b7da84636f89dcb6f45ef04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
