# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d5a630189cb3aa7fd572cb97d902727cc167c97df1edb7bed00ba7fba7ea71bdadf68201fb6bf5951c6d1df939fd9a65a0324e409665fd2320bb50e8ad2f16

test:
  secret_key_base: d599fa4bf610b1ebaedbb6dbc8030db11771003718b1084600639ebe9ecf9427291e710f71d5166a7d92fcf5be025ddd9d1bfd92431ccda05dd6cee38c517533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
